# Generated by Django 2.0 on 2018-02-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_tarefa', models.CharField(max_length=200)),
                ('data_criacao', models.DateTimeField(verbose_name='Data de Criação')),
                ('concluida', models.BooleanField()),
                ('data_conclusao', models.DateTimeField(verbose_name='Concluído em: ')),
            ],
        ),
    ]
